/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package outsonar

import org.eclipse.paho.client.mqttv3.MqttClient
import resources.SensorPort
import resources.ParkingState
import java.util.*

class OutSonarAdapter : SensorPort{
    private var distance: String = "9999"
	private var t : Timer? = null
	lateinit var alert: () -> Unit
    private val outsonarCB: OutSonarCallback = OutSonarCallback(this)
	private val client: MqttClient? = MqttClient("tcp://broker.hivemq.com:1883", MqttClient.generateClientId(), null)
	             
    init{
		client!!.setCallback(outsonarCB)
		client.connect()
		client.subscribe("sonar/data")
	}

	fun addAlert(lmbd: () -> Unit) {
		alert = lmbd
	}
	
	
	fun updateDistance(distance : String){
		this.distance = distance
		if(ParkingState.outdoorFree && distance.toInt() < 50){
			println("Scheduling timer")
			t = Timer()
			t!!.schedule(object : TimerTask() {
				override fun run() {
					alert()
					println("EIIII!")
				}
			}, 5000)
		}

		if(!ParkingState.outdoorFree && distance.toInt() >= 50){
			t?.cancel()
		}

		ParkingState.outdoorFree = distance.toInt() >= 50

	}
	
	override fun getValue() : String{
		return this.distance
	}
	
	/*
	fun setTimer(t : Timer){
		this.t = t
	}
	
	fun deleteTimer(){
		this.t = null
	}

	 */
		
		

}