/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sonar

import org.eclipse.paho.client.mqttv3.MqttClient
import org.eclipse.paho.client.mqttv3.MqttException
import org.eclipse.paho.client.mqttv3.MqttSecurityException
import Sonar.SonarInterface


class SonarAdapter : SonarInterface{
    private var distance: Int = 9999
    private val sonarCB: SonarCallback = SonarCallback(this)
	private val client: MqttClient? = MqttClient("tcp://localhost:1883", MqttClient.generateClientId())
	             
    init{
		client!!.setCallback(sonarCB)
		client.connect()
		client.subscribe("iot_data")
	}   
	
	
	fun updateDistance(distance : Int){
		this.distance = distance
	}
	
	override fun getDistance() : Int{
		return this.distance
	}
		

}