/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sonar

import org.eclipse.paho.client.mqttv3.MqttClient
import org.eclipse.paho.client.mqttv3.MqttException
import org.eclipse.paho.client.mqttv3.MqttSecurityException
import main.SensorPort

class SonarAdapter : SensorPort{
    private var distance: String = "9999"
    private val sonarCB: SonarCallback = SonarCallback(this)
	private val client: MqttClient? = MqttClient("tcp://localhost:1883", MqttClient.generateClientId())
	             
    init{
		client!!.setCallback(sonarCB)
		client.connect()
		client.subscribe("iot_data")
	}   
	
	
	fun updateDistance(distance : String){
		this.distance = distance
	}
	
	override fun getValue() : String{
		return this.distance
	}
		

}