/*
* This Java source file was generated by the Gradle 'init' task.
*/



import org.eclipse.californium.core.CoapResource;
import org.eclipse.californium.core.CoapServer;
import org.eclipse.californium.core.server.resources.CoapExchange
import org.eclipse.californium.core.CoapClient
import it.unibo.kactor.ApplMessage
import it.unibo.kactor.MsgUtil
//import it.unibo.connQak.connQakBase
//import it.unibo.connQak.connQakTcp
import org.eclipse.californium.core.coap.MediaTypeRegistry


class TransportTrolleyAdapter( val ipaddr : String, val context : String,  val destactor : String) {
	
	private val port: String = "8020"
	private var uriTrolley="coap://$ipaddr:$context/$destactor"
	private var client : CoapClient = CoapClient(uriTrolley)
	private lateinit var message : ApplMessage
	//private val connBasicRobot : connQakBase = conn
	
	fun sendCommand(move : String, msgid : String, author: String){
		
		//invio con dispatch
		message = MsgUtil.buildDispatch(author, msgid, move, destactor)
		client.put(message.toString(), MediaTypeRegistry.TEXT_PLAIN )
				
	}
	
	//fun sendRequest(){
		
		
	//}
    
}