/* Generated by AN DISI Unibo */ 
package trolley_controller

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Trolley_controller ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var currentTask : String = "NONE"
				//var ps : resources.ParkingState()
				lateinit var mv : String
				var x = 0
				var y = 0
				lateinit var ttAd : resources.ActuatorPort
				val HOME : Pair<String,String> = Pair("0", "0")
				val INDOOR : Pair<String,String> = Pair("5", "0")
				val OUTDOOR : Pair<String,String> = Pair("5", "4")
				val SLOT1 : Pair<String,String> = Pair("1", "1")
				val SLOT2 : Pair<String,String> = Pair("1", "2")
				val SLOT3 : Pair<String,String> = Pair("1", "3")
				val SLOT4 : Pair<String,String> = Pair("4", "1")
				val SLOT5 : Pair<String,String> = Pair("4", "2")
				val SLOT6 : Pair<String,String> = Pair("4", "3")
				
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						ttAd = resources.ActuatorFactory().getActuatorAdapter(resources.ActuatorType.TROLLEY) 
						println("trolleyController STARTS")
						planner.plannerUtil.loadRoomMapFromTxt( "parkingMap.txt"  )
						planner.plannerUtil.initAI(  )
						println("INITIAL MAP")
						planner.plannerUtil.showMap(  )
						planner.plannerUtil.startTimer(  )
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						 currentTask = "IDLE"
						resources.ParkingState.trolleyState = "idle"
						updateResourceRep( "trolley IDLE"  
						)
						println("trolleyController idle")
					}
					 transition(edgeName="t017",targetState="working",cond=whenRequest("moveToIn"))
					transition(edgeName="t018",targetState="working",cond=whenRequest("moveToOut"))
					transition(edgeName="t019",targetState="working",cond=whenRequest("moveToSlot"))
					transition(edgeName="t020",targetState="working",cond=whenDispatch("moveToHome"))
					transition(edgeName="t021",targetState="stopped",cond=whenDispatch("stop"))
				}	 
				state("working") { //this:State
					action { //it:State
						resources.ParkingState.trolleyState = "working"
						println("$name in ${currentState.stateName} | $currentMsg")
						println("trolley WORKING")
						updateResourceRep( "WORKING"  
						)
						if( checkMsgContent( Term.createTerm("moveToIn(MOVETOIN)"), Term.createTerm("moveToIn(WHERE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("trolley trip to INDOOR start")
								 
													planner.plannerUtil.planForGoal(INDOOR.first,INDOOR.second) 
													currentTask = "INDOOR"
											
													var mv : String = planner.plannerUtil.getNextPlannedMove()
													while(! mv.equals("")){
														ttAd.sendCommand(mv) 
														delay(1500)
														//CONTROLLARE STATO SE EVNTUALE ERRORE
														planner.plannerUtil.updateMap(mv)
														mv = planner.plannerUtil.getNextPlannedMove()	
												} 
								println("trolley trip to INDOOR end")
								updateResourceRep( "(5,0)"  
								)
								answer("moveToIn", "movedToIn", "movedToIn(done)"   )  
						}
						if( checkMsgContent( Term.createTerm("moveToOut(X)"), Term.createTerm("moveToOut(WHERE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("trolley trip to OUTDOOR start")
								 
													planner.plannerUtil.planForGoal(OUTDOOR.first,OUTDOOR.second) 
													currentTask = "OUTDOOR"
											
													var mv : String = planner.plannerUtil.getNextPlannedMove()
													while(! mv.equals("")){
														ttAd.sendCommand(mv) 
														delay(1500)
														//CONTROLLARE STATO SE EVNTUALE ERRORE
														planner.plannerUtil.updateMap(mv)
														mv = planner.plannerUtil.getNextPlannedMove()	
												} 
								println("trolley trip to OUTDOOR end")
								updateResourceRep( "(5,4)"  
								)
								answer("moveToOut", "movedToOut", "movedToOut(done)"   )  
								forward("moveToHome", "moveToHome(X)" ,"trolley_controller" ) 
						}
						if( checkMsgContent( Term.createTerm("moveToSlot(X)"), Term.createTerm("moveToSlot(SLOTNUM)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												var SLOTNUM = payloadArg(0).toInt()
												if( currentTask.equals("INDOOR"))
													currentTask = "PARKIN"
												else
													currentTask = "PARKOUT"
								println("trolley trip to slot $SLOTNUM start")
								
												when(SLOTNUM){
													1 -> {planner.plannerUtil.planForGoal(SLOT1.first, SLOT1.second);x=1;y=1}
													2 -> {planner.plannerUtil.planForGoal(SLOT2.first, SLOT2.second);x=1;y=2}
													3 -> {planner.plannerUtil.planForGoal(SLOT3.first, SLOT3.second);x=1;y=3}
													4 -> {planner.plannerUtil.planForGoal(SLOT4.first, SLOT4.second);x=4;y=1}
													5 -> {planner.plannerUtil.planForGoal(SLOT5.first, SLOT5.second);x=4;y=2}
													6 -> {planner.plannerUtil.planForGoal(SLOT6.first, SLOT6.second);x=4;y=3}
												}
												
												var mv = planner.plannerUtil.getNextPlannedMove()
												while(! mv.equals("")){
														ttAd.sendCommand(mv)
														delay(1500)	
														//CONTROLLARE STATO SE EVNTUALE ERRORE					
														planner.plannerUtil.updateMap(mv)
														mv = planner.plannerUtil.getNextPlannedMove()		
												} 
								updateResourceRep( "("+x+","+y+")"  
								)
								println("trolley trip to slot $SLOTNUM end")
								println("trolley $currentTask")
								if(  currentTask.equals("PARKIN")  
								 ){forward("moveToHome", "moveToHome(X)" ,"trolley_controller" ) 
								}
								answer("moveToSlot", "movedToSlot", "movedToSlot(done)"   )  
						}
						if( checkMsgContent( Term.createTerm("moveToHome(X)"), Term.createTerm("moveToHome(HOME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												currentTask = "HOME"
												planner.plannerUtil.planForGoal(HOME.first, HOME.second)
												var mv : String = planner.plannerUtil.getNextPlannedMove()
												while(! mv.equals("")){
														ttAd.sendCommand(mv) 
														delay(1500)
														//CONTROLLARE STATO SE EVNTUALE ERRORE
														planner.plannerUtil.updateMap(mv)
														mv = planner.plannerUtil.getNextPlannedMove()
												} 
								println("trolley in HOME")
							forward("goToIdle", "goToIdle(X)" ,"trolley_controller" )
							updateResourceRep( "(0,0)"
								)
						}
					}
					 transition(edgeName="t122",targetState="blocked",cond=whenDispatch("error"))
					transition(edgeName="t123",targetState="stopped",cond=whenDispatch("stop"))
					transition(edgeName="t124",targetState="working",cond=whenDispatch("moveToHome"))
					transition(edgeName="t125",targetState="working",cond=whenRequest("moveToIn"))
					transition(edgeName="t126",targetState="working",cond=whenRequest("moveToOut"))
					transition(edgeName="t127",targetState="working",cond=whenRequest("moveToSlot"))
					transition(edgeName="t128",targetState="idle",cond=whenDispatch("goToIdle"))
				}	 
				state("blocked") { //this:State
					action { //it:State
						println("trolleyController blocked")
						resources.ParkingState.trolleyState="stopped"
					}
				}	 
				state("stopped") { //this:State
					action { //it:State
						println("trolleyController stopped")
						resources.ParkingState.trolleyState = "stopped"
					}
					 transition(edgeName="t229",targetState="idle",cond=whenDispatchGuarded("resume",{ currentTask == "HOME" || currentTask == "IDLE"  
					}))
					transition(edgeName="t230",targetState="working",cond=whenDispatchGuarded("resume",{ currentTask == "PARKIN" || currentTask == "PARKOUT" || currentTask == "OUTDOOR" || currentTask == "INDOOR" 
					}))
				}	 
			}
		}
}
