version: '3'
services:
  wenv:
    image: docker.io/mfilo/virtualrobot
    ports:
      - 8090:8090
      - 8091:8091
  parkmanagerservice:
    image: docker.io/mfilo/carparkingv2
    ports:
      - 8081:8081/tcp
      - 8081:8081/udp
    depends_on:
      - wenv
